### ISSUE TITLE
Deprecated use of event

### ISSUE THREAD

**Issue by raggesilver** [dwilding/latex-brackets#2]
Not sure if you still support this project but in https://github.com/dwilding/latex-brackets/blob/master/gnome-3/latex-brackets.py you use `event.keyval`, in Gtk3 you should use event.key.keyval. Btw thanks for the code it helped me a lot creating my own :smile:

**Comment by dwilding** [comment]
Hey, sorry for the delay in getting back to you. I am not actively maintaining this project any more, but will make that change. Thanks for letting me know!
